#! /bin/bash
#
set -eu

cd "$HOME"

if [[ -z "${DOT2021:-}" ]]; then
  if [[ -d "${HOME}/dotfiles2021" ]]; then
    DOT2021="${HOME}/dotfiles2021"
  elif [[ -d "${HOME}/dotfiles/2021" ]]; then
    DOT2021="${HOME}/dotfiles/2021"
  else
    echo "Error: Could not find dotfiles" >&2
    exit 1
  fi
fi

ln -sf "${DOT2021}/git/gitconfig" .gitconfig
ln -sf "${DOT2021}/zsh/zshenv" .zshenv
