#! /bin/bash
#
set -eu

cd "$HOME"

if [[ -z "${DOT2021:-}" ]]; then
  if [[ -d "${HOME}/.dotfiles2021" ]]; then
    DOT2021="${HOME}/.dotfiles2021"
  elif [[ -d "${HOME}/dotfiles/2021" ]]; then
    DOT2021="${HOME}/dotfiles/2021"
  else
    echo "Error: Could not find dotfiles" >&2
    exit 1
  fi
fi

# Use a python3 venv for shell and neovim integrations.  This is much better
# than installing bindings in tons of different environments.
if type python3 > /dev/null; then
  if type pyvenv > /dev/null; then
    if ! [[ -d "${DOT2021}-python" ]]; then
      python3 -m venv "${DOT2021}-python"
      "${DOT2021}-python/bin/python3" -m pip install --upgrade pip wheel setuptools
      "${DOT2021}-python/bin/python3" -m pip install --upgrade powerline-status pynvim yapf
    fi
  else
    echo "Warning: python3-venv is missing."
    echo "On debian systems, fix with: apt-get install python3-venv"
    echo "powerline-status and nvim will not work correctly without python3 bindings"
  fi
else
  echo "Warning: python3 is not in PATH, skipping install of ~/.dotfiles2021-python"
  echo "powerline-status and nvim will not work correctly without python3 bindings"
fi

# Powerline
powerlineconf="$(find "${DOT2021}-python" -name powerline.conf)"
if [[ -e "${powerlineconf}" ]]; then
  (cd ~ && ln -sf "${powerlineconf}" .tmux.conf.powerline)
fi

ln_sf() {
  local target="$1"
  local path="$2"
  if [[ -d "${path}" ]]; then
    rm -rf "${path%/}"
  fi
  mkdir -p "$(dirname "${path%/}")"
  ln -sf "${target%/}" "${path%/}"
}

ln_sf "${DOT2021}/git/gitconfig" .gitconfig
ln_sf "${DOT2021}/zsh/zshenv" .zshenv
ln_sf "${DOT2021}/tmux/tmux.conf" .tmux.conf
ln_sf "${DOT2021}/config/powerline" .config/powerline
ln_sf "${DOT2021}/config/direnv/direnvrc" .config/direnv/direnvrc
# Vim and NeoVim
ln_sf "${DOT2021}/config/nvim/UltiSnips" .config/nvim/UltiSnips
ln_sf "${DOT2021}/config/nvim/autoload" .config/nvim/autoload
ln_sf "${DOT2021}/config/nvim/coc-settings.json" .config/nvim/coc-settings.json
ln_sf "${DOT2021}/config/nvim/init.vim" .config/nvim/init.vim
ln_sf "${DOT2021}/config/nvim/init.vim" .config/nvim/init.vim
ln_sf "${DOT2021}/vim/vimrc" .vimrc
ln_sf "${DOT2021}/vim/vimrc.settings" .vimrc.settings
ln_sf "${DOT2021}/vim/vimrc.before.local" .vimrc.before.local
ln_sf "${DOT2021}/vim/vimrc.bundles.local" .vimrc.bundles.local
ln_sf "${DOT2021}/vim/vimrc.local" .vimrc.local

echo "All done!  Dotfiles installed in ${DOT2021}"
echo "Log out and back in to activate the shell."
