# Determine where all of the dotfiles are located.
if [[ -r "${HOME}/.dotdir" ]]; then
  source "${HOME}/.dotdir"
fi

if [[ -z "${DOTDIR}" ]]; then
  DOTDIR="${HOME}/.dot"
fi

export VAULT_ADDR="https://vault.core.ois.run"

export ZDOTDIR="${DOTDIR}/zsh/zdotdir"
